### ISSUE TITLE
A small Help for me

### ISSUE THREAD

**Issue by PraneeshRV** [rjt-rockx/emerald#3]
can you please say what are the variables in config.js ?

please

**Comment by PraneeshRV** [comment]
@rjt-rockx  I am not copying your bot or self-hosting it. I need only level-up system like yours. I wont copy anything else.

**Comment by rjt-rockx** [comment]
Hey, a config can look like so:
```js
module.exports = {
	owners: [
		"youridhere"
	],
	token: "yourtokenhere",
	defaultPrefix: "yourprefixhere"
};

**Comment by PraneeshRV** [comment]
okk thanks
and what database you use?

**Comment by PraneeshRV** [comment]
and where will you connect it?

**Comment by rjt-rockx** [comment]
It uses quickdb, which isn't too complex tbh. You can find it at https://quickdb.js.org/

**Comment by PraneeshRV** [comment]
okk thanks
I will close this
