### ISSUE TITLE
Seeking Support 

### ISSUE THREAD

**Issue by PraneeshRV** [rjt-rockx/emerald#4]
Two years ago, when I was in discord, I loved discord.js-commando very much, I gone through a lot of bots using commando, I loved its command structures, and features, I'm back to discord after 1.5 years and sad that commando is gone forever. Is there any frameworks that's similar to commando these days?

**Comment by rjt-rockx** [comment]
Hey, sorry for the late reply
Slash-create is pretty similar to Commando and is built with slash commands in mind too
Check it out at https://slash-create.js.org/
